In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("sales_dataset.csv")
print(df.head())

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9


In [3]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [4]:
x=df.iloc[:,1:4].values
y=df.iloc[:,-1].values
print(x,y)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  35.7]
 [239.9  41.5

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)
print(x_train,x_test,y_train,y_test,sep="\n\n")

[[100.4   9.6   3.6]
 [ 67.8  36.6 114. ]
 [ 25.1  25.7  43.3]
 [107.4  14.   10.9]
 [112.9  17.4  38.6]
 [188.4  18.1  25.6]
 [ 43.1  26.7  35.1]
 [248.8  27.1  22.9]
 [166.8  42.    3.6]
 [240.1  16.7  22.9]
 [239.9  41.5  18.5]
 [234.5   3.4  84.8]
 [149.7  35.6   6. ]
 [170.2   7.8  35.2]
 [248.4  30.2  20.3]
 [184.9  21.   22. ]
 [222.4   3.4  13.1]
 [129.4   5.7  31.3]
 [216.8  43.9  27.2]
 [ 19.6  20.1  17. ]
 [ 13.1   0.4  25.6]
 [ 90.4   0.3  23.2]
 [ 18.7  12.1  23.4]
 [204.1  32.9  46. ]
 [  7.3  28.1  41.4]
 [147.3  23.9  19.1]
 [ 78.2  46.8  34.5]
 [228.   37.7  32. ]
 [205.   45.1  19.6]
 [229.5  32.3  74.2]
 [289.7  42.3  51.2]
 [123.1  34.6  12.4]
 [ 19.4  16.   22.3]
 [182.6  46.2  58.7]
 [265.6  20.    0.3]
 [165.6  10.   17.6]
 [218.5   5.4  27.4]
 [ 25.   11.   29.7]
 [232.1   8.6   8.7]
 [ 43.   25.9  20.5]
 [139.2  14.3  25.6]
 [139.3  14.5  10.2]
 [  5.4  29.9   9.4]
 [293.6  27.7   1.8]
 [281.4  39.6  55.8]
 [  8.7  48.9  75. ]
 [ 80.2   0.    9.2]
 [137.9  46.4

In [6]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [7]:
y_pred_train=regressor.predict(x_train)
y_pred_test=regressor.predict(x_test)

In [8]:
print(y_pred_train,y_pred_test,sep="\n\n")


[ 9.39399477 12.62747916  8.78635769 10.5179533  11.33960264 15.00851038
  9.8272915  19.49012351 18.48531666 17.1581701  21.75564603 14.2894321
 16.49877716 12.23132077 20.05212675 15.39167995 13.89311206  9.95484138
 21.10669498  7.55370471  3.58036634  7.16010711  6.01428431 18.43408246
  8.40828763 14.18834283 15.18549889 20.46698173 20.7982765  19.4380936
 24.14277244 15.062305    6.77221566 19.87050292 19.00733227 12.46604708
 14.04942242  6.08862152 15.31793431  9.70818084 12.01749864 12.09488231
  8.7277157  21.73239472 23.24592061 12.25073488  6.66285628 17.8293295
 16.32926536  8.97512204 20.46746223 20.77122182 24.1272017  10.23503295
 10.70759424 16.4917088  10.41584723  6.62154857 21.21556747 14.38421661
 15.57394979 10.08525717 14.77644286 13.77634013  8.45355979  8.8801801
 10.14367679  8.38362117 17.11580607 15.19221648 16.86305367 23.46810278
 13.46099757  9.76790461 18.18919366 14.83629355  5.38592446 12.89208872
 12.16469321 12.06979778 11.6347011  14.88127736  4.487

In [9]:
from sklearn.metrics import r2_score
r2_train = r2_score(y_train,y_pred_train)
r2_test = r2_score(y_test,y_pred_test)
print("Accuracy(Train) : ",r2_train)
print("Accuracy(Test) : ",r2_test)

Accuracy(Train) :  0.8991885185197644
Accuracy(Test) :  0.8500219587771267
